# Only RC file loaded on non-interactive zsh shells

# Homebrew
if [ -f /opt/homebrew/bin/brew ]; then
    eval "$(/opt/homebrew/bin/brew shellenv zsh)"
fi

# Platform-specific/private configuration
if [ -f $HOME/.zsh/platform-specific-profile ]; then
    source $HOME/.zsh/platform-specific-profile;
fi

# Mise shims directory
if [ -d "$HOME/.local/share/mise/shims" ]; then
    export PATH="$HOME/.local/share/mise/shims:$PATH";
fi
