# Aliases
if [ -f ~/.zsh/zshaliases ]; then
    source ~/.zsh/zshaliases
fi

# # Functions
if [ -f ~/.zsh/zshfunctions ]; then
    source ~/.zsh/zshfunctions
fi

# Git completion
# ZSH does git completion out of the box, but it needs to be enabled
autoload -Uz compinit && compinit

# Visual Studio Code
export PATH="$PATH:/Applications/Visual Studio Code.app/Contents/Resources/app/bin"

# Starship Configuration for Zsh
eval "$(starship init zsh)"

# Homebrew
# Removed a line that was adding, each time this was executed, the same eval to .zprofile
eval "$(/opt/homebrew/bin/brew shellenv)"

# Mint
export PATH="$PATH:$HOME/.mint/bin";

# Mise
eval "$($HOME/.local/bin/mise activate zsh)"

# Work-specific configuration
if [ -f ~/.zsh/work-config ]; then
    source ~/.zsh/work-config
fi

# Rbenv initialization
eval "$(rbenv init -)"

# Default folder
dev