# Prevent commands started with a space from being saved to history, ignore contiguous duplicates and certain commands
setopt HIST_IGNORE_SPACE
setopt HIST_IGNORE_DUPS
export HISTORY_IGNORE="c|l|s|ls"

# Aliases
if [ -f $HOME/.zsh_aliases ]; then
    source $HOME/.zsh_aliases
fi

# Git completion
# ZSH does git completion out of the box, but it needs to be enabled
autoload -Uz compinit && compinit

# Visual Studio Code
export PATH="$PATH:/Applications/Visual Studio Code.app/Contents/Resources/app/bin"

# Starship Configuration for ZSH
if command -V starship &>/dev/null; then
    eval "$(starship init zsh)"
fi

# Homebrew
# Removed a line that was adding the same eval to .zprofile each time this was executed
if [ -f /opt/homebrew/bin/brew ]; then
    eval "$(/opt/homebrew/bin/brew shellenv)";
fi

# Mint
if [ -d $HOME/.mint/bin ]; then
    export PATH="$PATH:$HOME/.mint/bin";
fi

# Mise
if [ -f $HOME/.local/bin/mise ]; then
    eval "$($HOME/.local/bin/mise activate zsh)";
fi

# Platform-specific/private configuration
if [ -f $HOME/.zsh/platform-specific-config ]; then
    source $HOME/.zsh/platform-specific-config;
fi

# This used to be the rbenv initialization section, but now ruby versions are being managed by Mise