# Prevent commands started with a space from being saved to $HOME/.zsh_history
setopt HIST_IGNORE_SPACE

# Aliases
if [ -f ~/.zsh/zshaliases ]; then
    source ~/.zsh/zshaliases
fi

# # Functions
if [ -f ~/.zsh/zshfunctions ]; then
    source ~/.zsh/zshfunctions
fi

# Git completion
# ZSH does git completion out of the box, but it needs to be enabled
autoload -Uz compinit && compinit

# Visual Studio Code
export PATH="$PATH:/Applications/Visual Studio Code.app/Contents/Resources/app/bin"

# Starship Configuration for Zsh
if command -V starship &>/dev/null; then
    eval "$(starship init zsh)"
fi

# Homebrew
# Removed a line that was adding, each time this was executed, the same eval to .zprofile
if [ -f /opt/homebrew/bin/brew ]; then
    eval "$(/opt/homebrew/bin/brew shellenv)";
fi

# Mint
export PATH="$PATH:$HOME/.mint/bin";

# Mise
if [ -f ~/.local/bin/mise ]; then
    eval "$($HOME/.local/bin/mise activate zsh)";
fi

# Work-specific configuration
if [ -f ~/.zsh/work-config ]; then
    source ~/.zsh/work-config;
fi

# Rbenv initialization
if command -V rbenv &>/dev/null; then
    eval "$(rbenv init -)"
fi

# Default folder
dev