# Get editor completions based on the config schema
# "$schema" = 'https://starship.rs/config-schema.json'

# Symbols used (https://www.nerdfonts.com/cheat-sheet)
# e0b4 , e0ba , e0bc , e0b0 , e691 , # f007 , f07c , e0a0 , f017 , f00ed 󰃭, e0c6 , f075a 󰝚

# Hints
# * When a string is enclosed by parenthesis, it doesn't render if all variables inside are None or empty
# * prev_bg and prev_fg are valid values for colors

# Pastel
#903284 #FFFFFF
#D65B71 #FFFFFF
#F0986F #000000
#7AB2D3 #000000
#2C597F #FFFFFF
#D0D0D0

# Blue
#3B237A #FFFFFF
#33658A #FFFFFF
#86BBD8 #000000
#ABABAB #000000
#B497FF

# Rainbow
#064A74 #FFFFFF
#7E1014 #FFFFFF
#B30020 #FFFFFF
#DD962C #000000
#FAD300 #000000
#00D000

# Optional first section
#[  ](fg:#FFFFFF bg:#903284)\
#[](fg:prev_bg bg:#D65B71)$username\

format = """
$username\
[](fg:prev_bg bg:#F0986F)$directory\
([](fg:prev_bg bg:#7AB2D3)$git_branch$git_status)\
[](fg:prev_bg bg:#2C597F)$time
[>](fg:#D0D0D0) 
"""

command_timeout = 750

add_newline = true

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "fg:#FFFFFF bg:#D65B71"
style_root = "fg:#FFFFFF bg:#D65B71"
format = "[  $user ]($style)"

[directory]
truncation_length = 3
truncation_symbol = "…/"
style = "fg:#000000 bg:#F0986F"
format = "[  $path ]($style)"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "📄 "
"Downloads" = "📥 "
"Music" = "󰝚 "
"Pictures" = "📷 "

[git_branch]
style = "fg:#000000 bg:#7AB2D3"
format = "[  $branch ]($style)"

[git_status]
style = "fg:#000000 bg:#7AB2D3"
format = '[$all_status$ahead_behind ]($style)'

[time]
disabled = false
time_format = "%T 󰃭 CW%V" # Hour:Minute:Second  CalendarWeek
style = "fg:#FFFFFF bg:#2C597F"
format = "[  $time [](#2C597F)]($style)"