# Get editor completions based on the config schema
#"$schema" = 'https://starship.rs/config-schema.json'

# Symbols reference https://www.nerdfonts.com/cheat-sheet
# e0b4 , e0ba , e0bc , e0b0 , e691 , # f007 , f07c , e0a0 , f017 , f075a 󰝚

# Blue
#3B237A #FFFFFF
#33658A #FFFFFF
#86BBD8 #000000
#ABABAB #000000
#B497FF

format = """
$username\
[](bg:#33658A fg:#3B237A)\
$directory\
[](bg:#86BBD8 fg:#33658A)\
[ ](fg:#000000 bg:#86BBD8)\
$git_branch\
$git_status\
[](fg:#86BBD8 bg:#ABABAB)\
$time\
[](fg:#ABABAB)
[>](fg:#B497FF) 
"""

command_timeout = 750

# Disable the blank line at the start of the prompt
# add_newline = true

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "fg:#ffffff bg:#3B237A"
style_root = "fg:#ffffff bg:#3B237A"
format = "[  $user ]($style)"

[directory]
style = "fg:#ffffff bg:#33658A"
format = "[  $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "📄 "
"Downloads" = "📥 "
"Music" = "󰝚 "
"Pictures" = "📷 "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[git_branch]
style = "fg:#000000 bg:#86BBD8"
format = '[[ $branch ](fg:#000000 bg:#86BBD8)]($style)'

[git_status]
style = "fg:#000000 bg:#86BBD8"
format = '[[($all_status$ahead_behind )](bg:#86BBD8 fg:#000000)]($style)'

[time]
disabled = false
time_format = "%T CW%V" # Hour:Minute:Second CalendarWeek
style = "fg:#000000 bg:#ABABAB"
format = '[[  $time ](fg:#000000 bg:#ABABAB)]($style)'