#!/usr/bin/env node

import { exec } from 'child_process'
import { chdir, cwd } from 'process'

chdir(process.env.MISE_ORIGINAL_CWD)
console.log(`Running in ${cwd()}`)
exec('npm outdated --json;', (_error, stdout, _stderr) => {
    const parsedJSON = JSON.parse(stdout)
    for (let key in parsedJSON) {
        const latestVersion = parsedJSON[key]['latest']
        console.log(`Installing ${key}@${latestVersion}`)
        exec(`npm install ${key}@${latestVersion}`)
    }
})

exec('npm audit fix')

console.log('NPM packages updated and audited. Remember to commit the changes')