# Shell commands
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -lah'
alias c='clear'

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# Git
run_git_command_if_git_repo() { if git status > /dev/null 2>&1; then git "$@"; else l; fi }
alias gd='run_git_command_if_git_repo diff'
alias gb='run_git_command_if_git_repo branch'
alias gc='run_git_command_if_git_repo checkout'
alias gp='run_git_command_if_git_repo pull'
alias grpo='run_git_command_if_git_repo remote prune origin'
alias s='run_git_command_if_git_repo status'

# Folders
alias dev='cd $HOME/dev'

# Applications
if uname -a | grep -i microsoft > /dev/null 2>&1; then
    alias brave='/mnt/c/Program\ Files/BraveSoftware/Brave-Browser/Application/brave.exe'
# TODO: alias for linux
fi